### ISSUE TITLE
check the following codes

### ISSUE THREAD

**Issue by WeiFoo** [ai-se/Caret#21]
- [x] R part including tuning and default 
- [x] DE code 
- [x] wrapper

**Comment by timm** [comment]
just to ask a dumb question- u r running on the same data sets as canada?

**Comment by WeiFoo** [comment]
Yes, both learners and datasets are exactly the same.

> +1-919-534-5251
> http://fuwei.us
> PhD Student in Computer Science,
> North Carolina State University.
>

**Comment by WeiFoo** [comment]
done!
